services:
  backend:
    build:
      context: .
    image: todoapi:latest
    container_name: todoapi
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://to-do-db-1:3306/tododb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db
    networks:
      - meu-app-network

  db:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: super_secret
      MYSQL_DATABASE: tododb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql  
    networks:
      - meu-app-network

networks:
  meu-app-network:
    driver: bridge

volumes:
  db-data: {}